services:
  evolution-api:
    image: atendai/evolution-api:v1.8.2
    container_name: evolution-api
    ports:
      - "8080:8080"
    environment:
      - AUTHENTICATION_API_KEY=homesync_key
      - DATABASE_ENABLED=false
      - STORE_MESSAGES=false
      - STORE_MESSAGE_UP_TO_DATE=false
      - STORE_CHATS=false
      - STORE_CONTACTS=false
      - CACHE_REDIS_ENABLED=false
      - CACHE_LOCAL_ENABLED=true
    volumes:
      - evolution_data:/evolution/data

volumes:
  evolution_data: